import { ProjectTemplate, TaskStatus, Priority } from '@/types';

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: 'tpl-website-launch',
    name: 'Website Launch',
    description: 'Complete website redesign and launch plan',
    icon: '🌐',
    tasks: [
      { title: 'Competitive research & analysis', description: 'Analyze competitor websites and identify best practices', status: 'done' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 0 },
      { title: 'Define site architecture', description: 'Create sitemap and information architecture document', status: 'done' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 1 },
      { title: 'Create wireframes', description: 'Design low-fidelity wireframes for all key pages', status: 'in_progress' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 2 },
      { title: 'Visual design mockups', description: 'Create high-fidelity design mockups in Figma', status: 'in_progress' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 3 },
      { title: 'Frontend development', description: 'Build responsive frontend with React/Next.js', status: 'todo' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 4 },
      { title: 'CMS integration', description: 'Set up and configure content management system', status: 'todo' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 5 },
      { title: 'SEO optimization', description: 'Implement meta tags, structured data, and performance optimizations', status: 'todo' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 6 },
      { title: 'Cross-browser testing', description: 'Test on Chrome, Firefox, Safari, Edge, and mobile browsers', status: 'backlog' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 7 },
      { title: 'Performance audit', description: 'Run Lighthouse audits and optimize for Core Web Vitals', status: 'backlog' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 8 },
      { title: 'Launch & monitoring', description: 'Deploy to production and set up monitoring dashboards', status: 'backlog' as TaskStatus, priority: 'urgent' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 9 },
    ],
  },
  {
    id: 'tpl-product-dev',
    name: 'Product Development',
    description: 'End-to-end product development workflow',
    icon: '🚀',
    tasks: [
      { title: 'Gather requirements', description: 'Collect and document product requirements from stakeholders', status: 'done' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 0 },
      { title: 'Create PRD', description: 'Write product requirements document with user stories', status: 'done' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 1 },
      { title: 'Technical architecture', description: 'Design system architecture and technology stack', status: 'in_progress' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 2 },
      { title: 'Sprint planning', description: 'Break down work into sprint-sized chunks', status: 'in_progress' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 3 },
      { title: 'Core feature implementation', description: 'Build the minimum viable product features', status: 'todo' as TaskStatus, priority: 'urgent' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 4 },
      { title: 'API development', description: 'Design and implement REST API endpoints', status: 'todo' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 5 },
      { title: 'Unit & integration tests', description: 'Write comprehensive test coverage for core modules', status: 'todo' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 6 },
      { title: 'QA testing', description: 'Perform end-to-end quality assurance testing', status: 'backlog' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 7 },
      { title: 'Beta release', description: 'Deploy beta version for internal testing', status: 'backlog' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 8 },
      { title: 'Production release', description: 'Final release to production with rollback plan', status: 'backlog' as TaskStatus, priority: 'urgent' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 9 },
    ],
  },
  {
    id: 'tpl-marketing',
    name: 'Marketing Campaign',
    description: 'Plan and execute a marketing campaign',
    icon: '📈',
    tasks: [
      { title: 'Market research', description: 'Analyze target audience and market opportunities', status: 'done' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 0 },
      { title: 'Define campaign strategy', description: 'Set goals, KPIs, and campaign messaging framework', status: 'done' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 1 },
      { title: 'Content calendar', description: 'Plan content schedule across all channels', status: 'in_progress' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 2 },
      { title: 'Create campaign assets', description: 'Design graphics, videos, and copy for all channels', status: 'in_progress' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 3 },
      { title: 'Email marketing setup', description: 'Configure email sequences and templates', status: 'todo' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 4 },
      { title: 'Social media campaigns', description: 'Launch and manage social media ad campaigns', status: 'todo' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 5 },
      { title: 'Landing page optimization', description: 'A/B test landing pages for conversion rate', status: 'todo' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 6 },
      { title: 'Campaign distribution', description: 'Execute multi-channel distribution plan', status: 'backlog' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 7 },
      { title: 'Analytics & reporting', description: 'Track campaign performance and generate reports', status: 'backlog' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 8 },
      { title: 'Post-campaign analysis', description: 'Conduct retrospective and document learnings', status: 'backlog' as TaskStatus, priority: 'low' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 9 },
    ],
  },
  {
    id: 'tpl-content',
    name: 'Content Calendar',
    description: 'Organize and manage content production',
    icon: '📝',
    tasks: [
      { title: 'Content audit', description: 'Review existing content and identify gaps', status: 'done' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 0 },
      { title: 'Keyword research', description: 'Identify target keywords and search intent', status: 'in_progress' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 1 },
      { title: 'Editorial guidelines', description: 'Create style guide and content standards', status: 'in_progress' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 2 },
      { title: 'Blog post: Getting started guide', description: 'Write comprehensive onboarding guide', status: 'todo' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 3 },
      { title: 'Blog post: Best practices', description: 'Write industry best practices article', status: 'todo' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 4 },
      { title: 'Social media graphics', description: 'Design shareable graphics for social platforms', status: 'backlog' as TaskStatus, priority: 'low' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 5 },
      { title: 'Video tutorials', description: 'Script and produce tutorial video series', status: 'backlog' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 6 },
      { title: 'Newsletter setup', description: 'Configure weekly newsletter template and automation', status: 'backlog' as TaskStatus, priority: 'low' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 7 },
    ],
  },
  {
    id: 'tpl-bug-tracking',
    name: 'Bug Tracking',
    description: 'Track and resolve software bugs',
    icon: '🔧',
    tasks: [
      { title: 'Login page crash on mobile Safari', description: 'App crashes when tapping the login button on Safari iOS 17', status: 'in_progress' as TaskStatus, priority: 'urgent' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 0 },
      { title: 'Dashboard data not refreshing', description: 'Dashboard metrics show stale data until manual refresh', status: 'in_progress' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 1 },
      { title: 'Email notifications sent twice', description: 'Users receiving duplicate email notifications', status: 'todo' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 2 },
      { title: 'Search results pagination broken', description: 'Clicking "next page" in search results shows empty page', status: 'todo' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 3 },
      { title: 'Dark mode contrast issues', description: 'Text hard to read in several dark mode components', status: 'todo' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 4 },
      { title: 'File upload progress not showing', description: 'Progress bar stays at 0% during file upload', status: 'backlog' as TaskStatus, priority: 'low' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 5 },
      { title: 'Timezone display incorrect', description: 'Timestamps show wrong timezone for EU users', status: 'backlog' as TaskStatus, priority: 'medium' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 6 },
      { title: 'Memory leak in chat component', description: 'Chat component causes memory usage to grow over time', status: 'backlog' as TaskStatus, priority: 'high' as Priority, dueDate: null, assigneeId: null, labelIds: [], order: 7 },
    ],
  },
];
